h.MingBase=MingClass.extend({init:function(a,
b,e){var d=Array.prototype.slice.call(a.qa("."+Wc)).pop();t.info("Options:",b);t.info("Config:",e.config);this.ancestors=[a.q("."+xa),a.q("."+Bb),a.q("."+tb),a.q("."+Ta),a.q("h1"),a.q("h4"),a.q("."+ea),a.q("."+rc)];d!==null&&d!==void 0&&this.ancestors.push(d);this.config=e.config;this.controller=e;this.loadedTime=((new Date).getTime()/1E3).round();this.setColorRules();b=this.config.embed.toggle.badge;e=!this.config.embed.on_site;if(b){var d=a.q("."+Ta),c=document.createElement("a"),g=document.createElement("img");
if(!d){d=document.createElement("div").addClass(Ta);a.q("."+pa).prependChild(d)}c.href=b.link;if(e)c.target="_blank";g.src=b.src;if(b.offset){c.style.cssText=c.style.cssText+(b.offset.x?"margin-left:"+b.offset.x/10+"em;":"");c.style.cssText=c.style.cssText+(b.offset.y?"margin-top:"+b.offset.y/10+"em;":"")}c.appendChild(g);this.ancestors.push(c);d.addClass(Vc+" "+b.name).clear().appendChild(c)}if(!this.config.video.hd)(a=a.q("."+Wa))&&a.remove()},checkRatio:function(){h.checkRatio(this.element,this.cover,
this.config)},coverIsTarget:function(a){for(var a=a.target||a.srcElement,b=this.ancestors,e=0,d=b.length;e<d;e++)if(a===b[e]||a.hasAncestor(b[e]))return false;return true},getSnapshot:function(a,b,e){if(a){var d=document.createElement("canvas"),c=d.getContext("2d"),b=b||a.videoWidth,e=e||a.videoHeight;d.attr({width:b,height:e});if(c){c.drawImage(a,0,0,b,e);return d}}return false},getSnapshotData:function(a,b,e,d){return this.getSnapshot(a,b,e,d).toDataURL(d||"image/png","")},getVideoUrl:function(a){var b=
this.config,e=this.controller.playableFiles,d=e[a],c=null;if(!e[a]){t.warn("No playable file of quality",a);return a==aa&&h.mobileCanPlaySD()?this.getVideoUrl(ya):c}if(((new Date).getTime()/1E3).round()-this.loadedTime>21E3){t.info("Old signature expired, getting a new one!",b.request.signature);e="//"+b.request.player_url+"/config/"+b.video.id+"/signature?prev_signature="+b.request.signature+"&prev_timestamp="+b.request.timestamp;e=(new XHR).getWithCredentials(e);b.request.signature=e.signature;
b.request.timestamp=e.timestamp;this.loadedTime=((new Date).getTime()/1E3).round();t.info("New signature:",b.request.signature)}if(d){c="//"+b.request.player_url+"/play_redirect";c=c+("?quality="+a)+("&codecs="+d)+("&clip_id="+b.video.id);c=c+("&time="+b.request.timestamp);c=c+("&sig="+b.request.signature);c=c+("&type=html5_"+this.controller.playerMode+"_"+(b.embed.on_site?"local":"embed"))}t.debug("Video URL: "+c);return c},setColorRules:function(a,b){var a=a||this.config.embed.color,b=b||this.config.embed.alt_color,
e=a==="fff"||a==="ffffff",d=function(a,b){var c=document.styleSheets[0];c.addRule?c.addRule(a,b):c.insertRule(a+"{"+b+"}",(c.cssRules||c.rules).length)},c=function(a){return"."+ba+" "+a},g=["a:link","a:visited","."+pa+" h1","."+pa+" h4 span"].map(c),h=["."+xa+" button."+Qa,"."+ea+" ."+O+" button","."+ea+" ."+O+" ."+Xa+" a"].map(c),f=["."+Y+" ."+Wa+" button:hover","."+Y+" ."+Wa+"."+ka+" button"].map(c),n=["."+Y+" ."+qc+" ."+sc,"> ."+O+" button","> ."+O+" ."+Xa+" a","."+ea+" ."+O+" button","."+ea+" ."+
O+" ."+Xa+" a","."+xa+" button."+Qa].map(c),c=["."+ea+" ."+O+"."+Wa+" strong"].map(c),t=["."+Xc+"."+Yc+" ul li."+Zc];if(this.controller.playerMode===qa){var o="."+ba+" ."+xa+" button:hover",i="."+N+" ."+Y+" ."+Bb+" ."+Ia+":hover";h.push(o,"."+ba+" ."+ea+" ."+O+"."+Ca+" ."+Xa+" button","."+ba+" ."+ea+" ."+O+"."+Ca+" ."+Xa+" a");f.push("."+ba+" ."+Y+" ."+Pc+" a:hover");n.push("."+ba+" ."+Y+" ."+tb+":hover",o,i);d("."+ba+" ."+bd+":hover","color:#f75342");d("."+ba+" ."+uc+":hover,."+ba+" ."+O+"."+Ca+
" ."+uc+":hover","background-color:#f75342")}d(g.join(","),"color:#"+a);d(n.join(","),"background-color:#"+a);d(t.join(","),"border-color:#"+a);d(h.join(","),"color:#"+(e?b:"fff"));d(f.join(","),"color:#"+(e?b:a));d(c.join(","),"background-color:#"+(e?b:a))}});h.Ming=h.MingBase.extend({init:function(a,b,e){function d(){l.addEventListener("canplay",g,false);l.addEventListener("canplaythrough",j,false);l.addEventListener("ended",f,false);l.addEventListener("error",n,false);l.addEventListener("loadedmetadata",
M,false);l.addEventListener("pause",o,false);l.addEventListener("play",i,false);l.addEventListener("progress",s,false);l.addEventListener("timeupdate",u,false);l.addEventListener("volumechange",r,false);l.addEventListener("waiting",m,false)}function c(){l.removeEventListener("canplay",g,false);l.removeEventListener("canplaythrough",j,false);l.removeEventListener("ended",f,false);l.removeEventListener("error",n,false);l.removeEventListener("loadedmetadata",M,false);l.removeEventListener("pause",o,
false);l.removeEventListener("play",i,false);l.removeEventListener("progress",s,false);l.removeEventListener("timeupdate",u,false);l.removeEventListener("volumechange",r,false);l.removeEventListener("waiting",m,false)}function g(a){Ca||s(a);if(Ya&&!ca){l.play();ca=true}V&&ca&&v.fire(ab)}function j(a){Ca||s(a);if(!Ya&&!ca){l.play();ca=true}v.fire(ab)}function f(e){l.pause();v.fire(Db,l.currentTime);la.fire(vb);if(Qa){l.currentTime=0;l.play()}else{document.webkitIsFullScreen||K.exitFullscreen();var f=
F.embed.outro.type;if(f==="custom")switch(F.embed.outro.data){case "nokia":v.fire(ua);var g=document.createElement("div");K.centerFitElement=R;K.EVENT_RESIZED=fa;K.EVENT_EMBED_BUTTON_PRESSED=wa;K.EVENT_VOTE_BUTTON_PRESSED=La;K.EVENT_LIKE_BUTTON_PRESSED=fa;(new XHR).get(b.html_path+"/ming_overlay_"+F.embed.outro.data+".html?"+(new Date).getTime(),function(b){g.html(b).addClass(bc);a.insertBefore(g,Ja.nextSibling);(b=g.q("script"))&&(new Function(b.innerHTML)).call(K);Ja.addClass(y);Va.element.parentElement.addClass(y);
D();Ka=true;G();v.bind(S,function Rb(){v.unbind(S,Rb);a.removeChild(g);Ka=W=false;Va.element.parentElement.removeClass(y)});v.bind(X,function(){Ja.addClass(y);Va.element.parentElement.addClass(y)})});break;default:v.fire(va,{controls:true,sidedock:true});v.fire(H,{name:F.embed.outro.data})}else{if(f==="nothing"){G();B();Ka=W=true;v.bind(S,function vc(){v.unbind(S,vc);Ka=W=false})}else if(f==="beginning"){D();G();v.fire(Jb);Ka=W=true;v.bind(S,function Rb(){v.unbind(S,Rb);Ka=W=false;d();s(e)});l.pause();
l.currentTime=0;setTimeout(function(){v.fire(Kb,0);v.fire(ma,{currentTime:0,progress:0,hours:(F.video.duration/3600%60).floor(),minutes:(F.video.duration/60%60).floor(),seconds:(F.video.duration%60).floor()});c()},0);Ja.css({backgroundImage:"url("+Ja.attr("data-thumb")+")",backgroundColor:"#000"});return}v.fire(va,{controls:true,sidedock:true});v.fire(H,{name:"outro"})}}}function n(){var a=l.error;if(a instanceof MediaError)switch(a.code){case MediaError.MEDIA_ERR_ABORTED:case MediaError.MEDIA_ERR_DECODE:case MediaError.MEDIA_ERR_NETWORK:t.error("There was an issue playing this video.",
$m.findKey(a.code,MediaError),a);v.fire(H,{name:"error",isSticky:true});break;case MediaError.MEDIA_ERR_SRC_NOT_SUPPORTED:t.error("Source file not supported, attempting to fall back to a lower quality...");e.playableFiles[da]=false;a=w(da);if(!a){v.fire(H,{name:"error",isSticky:true});break}l.attr("src",a).play()}}function M(){pb=l.videoWidth/l.videoHeight;F.video.duration=l.duration;if(F.embed.time>0)l.currentTime=F.embed.time;t.info("Aspect ratio:",pb);t.info("Total bytes:",l.totalBytes)}function o(){if(!Hb){v.fire(ua,
l.currentTime);l.ended||la.fire(bb)}}function i(){if(ub){ub.remove();W=ub=false}ca=true;p();v.fire(ab);if(!Hb){v.fire(na);la.fire(cb)}}function s(){if(l.buffered.length>0&&!Hb){var a=l.buffered.end(0)/l.duration;v.fire(Kb,a);la.fire(db,{bytesLoaded:-1,bytesTotal:-1,percent:a.toFixed(3),duration:l.duration.toFixed(3)})}Ca=true}function u(){var a=l.currentTime/l.duration;if(a>=0){v.fire(ma,{currentTime:l.currentTime.round(),progress:a,hours:(l.currentTime/3600%60).floor(),minutes:(l.currentTime/60%
60).floor(),seconds:(l.currentTime%60).floor()});F.embed.api.on&&(!Hb&&l.currentTime>0)&&la.fire(eb,{seconds:l.currentTime.toFixed(3),percent:a.toFixed(3),duration:l.duration.toFixed(3)})}}function r(){v.fire(Ob,l.volume)}function m(){v.fire(wb)}function C(a){K.coverIsTarget(a)&&v.fire(L)}function q(){if(document.webkitIsFullScreen){a.addClass(Ia);v.fire(Yb);z();N();F.request.cookie.scaling?T():aa()}else{ta=false;l.webkitEnterFullscreen();V||v.fire(L)}}function w(a){for(var a=kc.slice(kc.indexOf(a)),
b=null;b===null&&a.length;){da=a.shift();b=K.getVideoUrl(da)}v.fire(gb,da);return b}function k(){if(l){if(!Ga&&!W&&l.currentTime>=Pb){v.fire($a,{controls:true});if(document.webkitIsFullScreen){K.element.style.cursor="none";Za=e.ua.safari?1:2}}l.currentTime<Pb&&setTimeout(k,500)}}function D(){if(l){!Da&&(!Ka&&l.currentTime>=Pb)&&v.fire($a,{sidedock:true});l.currentTime<Pb&&setTimeout(D,500)}}function E(){Da=Ga=false;k();D();clearTimeout(rb);clearTimeout(qb)}function G(){v.fire(va,{controls:!W,sidedock:!Ka})}
function B(){v.fire(va,{sidedock:!Ka})}function z(){Da=Ga=false;G();B()}function p(a){Ja.css({backgroundImage:"none",backgroundColor:a?"#000":"transparent"})}function O(){a.addEventListener("mousemove",J,false);a.addEventListener("mouseout",function(a){a=a.relatedTarget;(a===null||this!==a&&!a.hasAncestor(this))&&E()},false);window.addEventListener("blur",E,false)}function N(){clearTimeout(rb);clearTimeout(qb);rb=setTimeout(k,lc);qb=setTimeout(D,lc)}function J(a){if(Za===0){K.element.style.cursor=
"default";G();Da=Bb.mousedOver(a.target);Ga=Cb.mousedOver(a.target);N()}else Za--}function x(a){v.fire(P,a)}function A(b){b.target.hasAncestor(a)?qa():ra()}function R(b,c,d){var e;e=a.clientWidth/a.clientHeight;var f=c/d,c=d=0;if(e>=f){c=a.clientHeight;d=(f*a.clientHeight).toFixed(2)}else if(e<f){d=a.clientWidth;c=(a.clientWidth/f).toFixed(2)}e=d;b.tagName=="IMG"?b.attr({width:e,height:c}):b.css({width:e+"px",height:c+"px"});b.css({position:"absolute",top:"50%",left:"50%",marginLeft:-(e/2).toFixed(2)+
"px",marginTop:-(c/2).toFixed(2)+"px"});return b}function T(){Ra=true;Ua.css({width:"100%",height:"100%",position:"",top:"",left:"",marginLeft:"",marginTop:""})}function aa(){Ra=false;var b=Math.min(V?l.videoWidth:F.video.width,a.clientWidth),c=Math.min(V?l.videoHeight:F.video.height,a.clientHeight);Ua.css({width:b+"px",height:c+"px",position:"absolute",top:"50%",left:"50%",marginLeft:-(b/2).toFixed(2)+"px",marginTop:-(c/2).toFixed(2)+"px"})}function ia(a){if(!l.paused){v.fire(S);J(a)}if(V&&!ca){o(false);
ca=true}}function ka(a){if(V){if(l.paused){v.fire(S);J(a)}}else v.fire(L)}function ja(a){function b(){la.fire(fb,{seconds:l.currentTime.toFixed(3),percent:(l.currentTime/l.duration).toFixed(3),duration:l.duration.toFixed(3)})}var c=a.data.toInt().limit(0,l.duration||F.video.duration);if(V){l.currentTime=c;b()}else{v.fire(L);l.addEventListener("durationchange",function vc(){l.removeEventListener("durationchange",vc,false);l.currentTime=c;b()},false)}J(a)}function sa(a){window.console&&window.console.warn&&
console.warn("API method "+a.name+" not supported in this player.");l.pause();l.src="";l.remove();v.fire(X);v.fire(ab);G();B();W=Ka=true;Ja.css("background-image",Ja.attr("data-poster"));v.fire(oc)}function Ea(a){F.embed.color=a.data;K.setColorRules();v.fire(Eb)}function Fa(a){Qa=a.data}function Ha(a){l.volume=a.data.limit(0,1)}function U(a){var b=false;switch(a.name){case ga:b=l.currentTime.toFixed(3);break;case ha:b=F.video.duration.toFixed(3);break;case Aa:b=l.volume.toFixed(3);break;case oa:b=
V&&ca?!!l.paused:!V;break;case xb:b=!!Qa;break;case Ma:b=l.videoWidth>0?l.videoWidth:F.video.width;break;case Na:b=l.videoHeight>0?l.videoHeight:F.video.height}zb.sendBack(a.name,b)}function qa(){window.addEventListener("keydown",Xa,false);window.addEventListener("keyup",Wa,false)}function ra(){window.removeEventListener("keydown",Xa,false);window.removeEventListener("keyup",Wa,false)}function Ta(a){var b=!!$m.findKey(a.keyCode,Q);switch(document.activeElement.tagName){case "TEXTAREA":case "INPUT":b=
false}if(a.altKey||a.ctrlKey||a.metaKey)b=false;return b}function Wa(a){Sa=0;if(Ta(a)){if(Ib){l.play();Ib=false}Cb.unlockPlayButton()}}function Xa(a){if(Ta(a)){var b=a.keyCode,c=false;Sa++;switch(b){case Q.escape:K.exitFullscreen();break;case Q.space:V?v.fire(S):v.fire(L);c=true;break;case Q.up:case Q.down:var d=l.volume*Gb,e=b===Q.down?d.floor():d.ceil(),b=d.toPrecision(2)!==e.toPrecision(2)?e/Gb:(e+(b==Q.down?-1:1))/Gb;l.volume=b.limit(0,1);break;case Q.left:case Q.right:c=Sa;if(V&&ca){Cb.lockPlayButton();
if(!Ib){Ib=!l.paused;l.pause()}c=($m.fibonacci((c/3).floor())/100).limit(1/l.duration,0.07)*l.duration;l.currentTime=b==Q.left?l.currentTime-c:l.currentTime+c}c=true;break;case Q.e:case Q.E:v.fire(wa);break;case Q.f:case Q.F:v.fire(Qb);break;case Q.l:case Q.L:v.fire(fa);break;case Q.s:case Q.S:v.fire(ib);break;case Q.w:case Q.W:v.fire(hb)}if(c){z();N()}a.preventDefault()}}sb=1;this._super(a,b,e);var K=this,F=e.config,Ya=true,ta=!!a.webkitRequestFullScreen,da=false,V=false,ca=false,Hb=false,Qa=!!F.embed.loop,
Ca=false,Ib=false,ob=false,Ra=true,Sa=0,pb=0,Da=false,Ga=false,Ka=false,W=false,Za=0,yb=null,qb=null,rb=null,zb=e.api,la=zb.events,l=document.createElement("video"),Ua=a.q("."+Nc),Ja=a.q("."+Mb),ub=null,v=new EventManager,Q={escape:27,space:32,E:69,e:101,F:70,f:102,L:76,l:108,S:83,s:115,W:87,w:119,up:38,down:40,left:37,right:39},Va,Bb,Cb,tb;K.element=a;K.cover=Ja;K.events=v;K.exitFullscreen=function(){T();document.webkitIsFullScreen?document.webkitCancelFullScreen():l.webkitSupportsFullscreen&&l.webkitDisplayingFullscreen&&
l.webkitExitFullscreen();a.hasClass(Ab)&&v.fire(Zb);a.hasClass(Ia)&&v.fire($b);a.removeClass(Ia);a.removeClass(Ab);document.body.removeClass(Ab);v.fire(P)};v.bind(L,function(){a.removeEventListener("click",C,false);l.attr({src:w(da),height:"100%",width:"100%"});Ua.prependChild(l);l.load();v.fire(wb);la.fire(cb);p(true);a.q("."+pa).addClass(I);a.addEventListener("dblclick",function(a){K.coverIsTarget(a)&&v.fire(Qb)});a.addEventListener("click",function(a){K.coverIsTarget(a)&&v.fire(S)});O();N();V=
true}).bind(S,function(){if(V&&!ca){v.fire(ua);la.fire(bb);ca=true}else l.paused||l.ended?l.play():l.pause()}).bind(Sb,function(){Hb=true;Ib=!l.paused;l.pause();ob=W;W=true}).bind(mc,function(a){l.currentTime=l.duration*a.data;la.fire(fb,{seconds:l.currentTime.toFixed(3),percent:a.data.toFixed(3),duration:l.duration.toFixed(3)});ca||l.play()}).bind(Tb,function(){(Ib||!Ca)&&l.play();ob||(W=false);setTimeout(function(){Hb=false},10)}).bind(Ub,function(){W=true}).bind(nc,function(a){l.volume=a.data}).bind(Vb,
function(){W=false;clearTimeout(yb);yb=setTimeout(function(){h.setCookie(Jc,(l.volume*100).round())},1E3)}).bind(H,function(a){tb.get(a.data);a.data.isToggle||l.pause()}).bind(X,function(){tb.hide()}).bind(Qb,function(){if(a.hasClass(Ab)||a.hasClass(Ia))K.exitFullscreen();else if(ta&&a.webkitRequestFullScreen){E();a.webkitRequestFullScreen();setTimeout(q,320)}else if(l.webkitSupportsFullscreen){E();l.webkitEnterFullscreen()}else if(V===true||!ta&&F.embed.on_site){a.addClass(Ab);document.body.addClass(Ab);
v.fire(Xb)}v.fire(P)}).bind(P,function(){K.checkRatio();s();u()}).bind(Nb,function(a){if(F.security.hd_embed){da=da===Z?ya:Z;F.request.cookie.hd=da===Z?1:0;v.fire(gb,da);h.setCookie(ec,da===Z?1:0);v.fire(H,{name:"hd",isToggle:true,hideTime:2E3});if(V&&!ca){l.src=K.getVideoUrl(da);l.load();l.play()}else if(ca){var b=l.currentTime,c=!l.paused;Cb.lockPlayButton();W=true;l.pause();ub=document.createElement("canvas").addClass(Oc);Ua.insertBefore(ub,Ja);var d=ub.getContext("2d");d&&d.drawImage(l,0,0,ub.width,
ub.height);setTimeout(function(){l.src=K.getVideoUrl(da);l.load();l.addEventListener("loadedmetadata",function Rb(){l.removeEventListener(a.type,Rb,false);l.currentTime=b;Ra||aa()},false);l.addEventListener("seeked",function ed(){l.removeEventListener(a.type,ed,false);if(c){l.play();c=false}W=false;Cb.unlockPlayButton()},false)},250)}}else v.fire(H,{name:"hd"})}).bind(fa,function(){if(F.user.status.logged_in){F.user.liked=F.user.liked?0:1;(new XHR).postWithCredentials("//"+F.request.player_url+"/like/"+
F.video.id,"status="+F.user.liked,$m.emptyFunction);typeof like_clip!="undefined"&&like_clip({like_it:F.user.liked,clip_id:F.video.id})}setTimeout(function(){v.fire(H,{name:"like",isToggle:F.user.status.logged_in,hideTime:500})},10)}).bind(hb,function(){if(F.user.status.logged_in){F.user.watch_later=F.user.watch_later?0:1;(new XHR).postWithCredentials("//"+F.request.player_url+"/watch_later/"+F.video.id,"status="+F.user.watch_later,$m.emptyFunction)}setTimeout(function(){v.fire(H,{name:"watchlater",
isToggle:F.user.status.logged_in,hideTime:2E3})},10)}).bind(ib,function(){setTimeout(function(){v.fire(H,{name:"share"})},10)}).bind(wa,function(){setTimeout(function(){v.fire(H,{name:"embed"})},10)}).bind(La,function(){setTimeout(function(){v.fire(H,{name:"vote"})},10)}).bind(Wb,function(a){a=!a.data.getIsActive();h.setCookie(Kc,a?1:0);F.request.cookie.scaling=a?1:0;a?T():aa()});F.embed.api.on&&la.bind(jb,ia).bind(kb,ka).bind(lb,ja).bind(mb,sa).bind(za,Ea).bind(Oa,Fa).bind(Pa,Ha).bind(ga,U).bind(ha,
U).bind(Aa,U).bind(oa,U).bind(xb,U).bind(Ma,U).bind(Na,U);K.destroy=function(){ra();if(V){c();setTimeout(function(){l.pause();l.src="";l.parentNode.removeChild(l);l=null},0)}F.embed.api.on&&la.unbind(jb,ia).unbind(kb,ka).unbind(lb,ja).unbind(mb,sa).unbind(za,Ea).unbind(Oa,Fa).unbind(Pa,Ha).unbind(ga,U).unbind(ha,U).unbind(Aa,U).unbind(oa,U).unbind(xb,U).unbind(Ma,U).unbind(Na,U);window.removeEventListener("focus",qa,false);window.removeEventListener("blur",ra,false);window.removeEventListener("click",
A,false);window.removeEventListener("resize",x,false)};a.addEventListener("click",C,false);document.qa("."+ba).length==1&&qa();window.addEventListener("focus",qa,false);window.addEventListener("blur",ra,false);window.addEventListener("click",A,false);a.addEventListener("webkitfullscreenchange",function(){document.webkitIsFullScreen===false&&K.exitFullscreen();setTimeout(function(){v.fire(P)},250)},false);Va=new h.Ming.Intro(a.q("."+pa),K);Bb=new h.Ming.Sidedock(a.q("."+xa),K);Cb=new h.Ming.Controls(a.q("."+
Y),K);tb=new h.Ming.Overlays(a.q("."+ea),b.html_path,b.css_path,K);l.volume=F.request.cookie.volume/100;v.fire(Ob,l.volume);K.stats=new h.Ming.Stats(e.config,e,K);da=F.request.cookie.hd&&F.security.hd_embed&&F.video.hd?Z:ya;v.fire(gb,da);!ta&&!F.embed.on_site&&Cb.setFullScreenSupported(false);d();K.checkRatio();window.addEventListener("resize",x,false);v.fire(P);a.parentNode.api_seekTo=function(a){ja({data:a})};a.removeClass(Ba);la.fire(nb);t.info("Welcome to the Vimeo desktop HTML player v"+b.version+
"!");F.embed.autoplay&&v.fire(L)}});h.Ming.Stats=h.Stats.extend({init:function(a,b,e){function d(){z=w}function c(){var a=100*(w-z);0<a&&i("Scrub",a.round());z=null}function g(){C&&(B=(new Date).getTime())}function j(){if(C&&null!==B){var a=(new Date).getTime()-B;10<a&&i((m===aa?"Mobile":m.toUpperCase())+
" Buffer Time",a);B=null}}function f(){i("Play Button Pressed")}function n(){E=!0}function h(){E=!1;i("Volume Changed",(100*D).round())}function o(a){!E&&0!==D&&i("Volume Changed",(100*a.data).round());D=a.data}this._super(a,b);var i=this.googleLog,s=this.vimeoLog,u=this.partialPlayLog,r=e.events,m="",C=!1,q=!1,w=0,k=0,D=0,E=!1,G=null,B=null,z=null,p=!1,y=!1,t=!1,J=!1;r.bind(L,function(){G=(new Date).getTime();i("Play");e.events.bind(S,f)}).bind(na,function(){C||(C=!0,i((m===aa?"Mobile":m.toUpperCase())+
" Load Time",(new Date).getTime()-G))}).bind(ua,function(a){u(a.data,m)}).bind(Db,function(a){q||(q=!0,s("finish",m),i("Finish"),u(a.data,m))}).bind(ma,function(a){var b=a.data.progress,a=a.data.currentTime;z||(!t&&0.75<=b?(p=y=t=!0,u(a,m)):!y&&0.5<=b?(p=y=!0,u(a,m)):!p&&0.25<=b&&(p=!0,u(a,m)));w=b;k=a}).bind(Nb,function(){i("HD "+(a.request.cookie.hd?"on":"off"))}).bind(fa,function(){i(a.user.liked?"Liked":"Unliked")}).bind(hb,function(){i("Watch Later "+(a.user.watch_later?"Added":"Removed"))}).bind(ib,
function(){i("Share Button Pressed")}).bind(wa,function(){i("Embed Button Pressed")}).bind(La,function(){i("Vote Button Pressed")}).bind(gb,function(a){m=a.data});b.playerMode===qa&&r.bind(wb,g).bind(ab,j).bind(Sb,d).bind(Tb,c).bind(Ub,n).bind(Vb,h).bind(Ob,o);30>a.video.duration&&(t=p=!0);b.playerMode!==ia&&(window.onbeforeunload=window.onunload=function(){if(C&&!J){i("Progress",(w*100).round());u(k,m,true);J=true}});this.clientLog()}});h.Ming.Canvas={playIcon:{draw:[{beginPath:null},{moveTo:[0,0]},{lineTo:[20,10]},{lineTo:[0,20]},{fill:null}],translate:{x:0,y:0},scale:1},pauseIcon:{draw:[{fillRect:[0.5,
0,6.5,20]},{fillRect:[12,0,6.5,20]}]},heartIcon:{draw:[{beginPath:null},{moveTo:[10.19,2.98]},{bezierCurveTo:[9.27,2.32,9.24,1.83,8.5,1.37]},{bezierCurveTo:[5.34,-0.58,0.18,1.16,0.5,5.7]},{bezierCurveTo:[0.57,6.72,1.09,7.63,1.56,8.22]},{bezierCurveTo:[3.7,10.93,8.35,12.66,10.34,15.28]},{bezierCurveTo:[12.25,11.63,19.57,10.35,19.79,5.56]},{bezierCurveTo:[20.01,0.85,14.34,-0.77,11.33,1.79]},{bezierCurveTo:[11.33,1.79,10.69,2.19,10.19,2.98]},{closePath:null},{fill:null}],translate:{x:5,y:2},scale:1},
brokenHeartIcon:{draw:[{lineTo:[8.97,5.72]},{lineTo:[11.37,7.22]},{lineTo:[8.97,9.42]},{lineTo:[9.97,12.12]},{lineTo:[8.27,9.42]},{lineTo:[10.27,7.32]},{lineTo:[8.16,6.02]},{lineTo:[9.27,2.32]}],translate:{},scale:1},watchLaterIcon:{draw:[{beginPath:null},{moveTo:[8.64,4.68]},{lineTo:[9.56,4.68]},{lineTo:[10.28,11.21]},{lineTo:[7.93,11.21]},{lineTo:[8.64,4.68]},{closePath:null},{fill:null},{beginPath:null},{moveTo:[13.19,13.65]},{lineTo:[12.7,14.14]},{lineTo:[7.58,10.4]},{lineTo:[9.44,8.5]},{lineTo:[13.19,
13.65]},{closePath:null},{fill:null},{lineWidth:"2"},{beginPath:null},{moveTo:[17.64,9.5]},{bezierCurveTo:[17.64,13.99,13.99,17.64,9.5,17.64]},{bezierCurveTo:[5,17.64,1.36,13.99,1.36,9.5]},{bezierCurveTo:[1.36,5,5,1.36,9.5,1.36]},{bezierCurveTo:[13.99,1.36,17.64,5,17.64,9.5]},{closePath:null},{stroke:null}],translate:{x:5.5,y:0.5},scale:1},shareIcon:{draw:[{beginPath:null},{arc:[5,14,2,0,2*Math.PI,!1]},{arc:[8.5,10.5,2,0,2*Math.PI,!1]},{arc:[12,7,2,0,2*Math.PI,!1]},{fill:null},{lineCap:"round"},{lineJoin:"round"},
{lineWidth:"2.5"},{beginPath:null},{moveTo:[12.5,2]},{lineTo:[17.5,3]},{lineTo:[16.5,8]},{stroke:null},{beginPath:null},{arc:[26,6,2,0,2*Math.PI,!1]},{arc:[22.5,9.5,2,0,2*Math.PI,!1]},{arc:[19,13,2,0,2*Math.PI,!1]},{fill:null},{beginPath:null},{moveTo:[14.5,12]},{lineTo:[13.5,17]},{lineTo:[18.5,18]},{stroke:null}],translate:{x:0,y:0},scale:1},embedIcon:{draw:[{lineWidth:"1.7857"},{lineCap:"round"},{beginPath:null},{moveTo:[18.65,5]},{lineTo:[14.36,15]},{stroke:null},{lineWidth:"2.8572"},{beginPath:null},
{moveTo:[23,12.85]},{lineTo:[26.5,9.85]},{lineTo:[22.93,7.14]},{stroke:null},{beginPath:null},{moveTo:[9.93,7.14]},{lineTo:[6.5,10]},{lineTo:[10.07,12.85]},{stroke:null}],translate:{x:-3.5,y:-1},scale:1.1},voteIcon:{draw:[{beginPath:null},{moveTo:[18,16.941]},{bezierCurveTo:[18,17.525,17.526,18,16.941,18]},{lineTo:[1.059,18]},{bezierCurveTo:[0.474,18,0,17.525,0,16.941]},{lineTo:[0,1.059]},{bezierCurveTo:[0,0.474,0.474,0,1.059,0]},{lineTo:[16.942,0]},{bezierCurveTo:[17.526,0,18,0.474,18,1.059]},{lineTo:[18,
16.941]},{closePath:null},{moveTo:[15.422,5.854]},{bezierCurveTo:[15.58,5.665,15.556000000000001,5.385,15.369,5.229]},{lineTo:[13.222,3.42]},{bezierCurveTo:[13.033999999999999,3.262,12.756,3.285,12.597999999999999,3.473]},{lineTo:[7.368999999999999,9.683]},{lineTo:[4.868999999999999,7.576]},{bezierCurveTo:[4.681,7.418,4.401,7.443,4.245,7.63]},{lineTo:[2.437,9.777]},{bezierCurveTo:[2.279,9.964,2.303,10.242,2.49,10.4]},{lineTo:[7.461,14.587]},{bezierCurveTo:[7.649,14.745,7.928,14.722,8.085,14.533999999999999]},
{lineTo:[8.095,14.521999999999998]},{bezierCurveTo:[8.13,14.498999999999999,8.163,14.470999999999998,8.192,14.435999999999998]},{lineTo:[15.422,5.854]},{fill:null}],translate:{x:6,y:2},scale:0.9},watchIcon:{draw:[{beginPath:null},{moveTo:[0,0]},{lineTo:[25,0]},{lineTo:[25,25]},{lineTo:[0,25]},{closePath:null},{beginPath:null},{moveTo:[12.5,0]},{bezierCurveTo:[5.612,0,0,5.611,0,12.509]},{bezierCurveTo:[0,19.407,5.612,25.019,12.509,25.019]},{bezierCurveTo:[19.406,25.019,25.018,19.407,25.018,12.509]},
{bezierCurveTo:[25.018,5.611,19.406,0,12.509,0]},{closePath:null},{moveTo:[12.5,22.874]},{bezierCurveTo:[6.794,22.874,2.144,18.225,2.144,12.509]},{bezierCurveTo:[2.144,6.794,6.794,2.144,12.509,2.144]},{bezierCurveTo:[18.224,2.144,22.874,6.794,22.874,12.509]},{bezierCurveTo:[22.874,18.225,18.225,22.874,12.509,22.874]},{closePath:null},{moveTo:[8.718,6.72]},{lineTo:[8.718,18.698]},{lineTo:[20.064,12.709]},{lineTo:[8.718,6.72]},{closePath:null},{fill:null},{stroke:null}],translate:{x:0,y:0},scale:0.9},
fullscreenIcon:{draw:[{beginPath:null},{moveTo:[6,6]},{lineTo:[5.9,2]},{lineTo:[4.9,3]},{lineTo:[2.9,1]},{lineTo:[1,2.9]},{lineTo:[3,4.9]},{lineTo:[2,5.9]},{closePath:null},{fill:null}],translate:{x:6,y:6},scale:1},unfullscreenIcon:{draw:[{beginPath:null},{moveTo:[-1,-1]},{lineTo:[-1.1,-5]},{lineTo:[-2.1,-4]},{lineTo:[-4.1,-6]},{lineTo:[-6,-4.1]},{lineTo:[-4,-2.1]},{lineTo:[-5,-1.1]},{closePath:null},{fill:null}],translate:{x:6,y:6},scale:1},plusIcon:{draw:[{strokeStyle:"ffffff"},{lineWidth:"37"},
{lineCap:"round"},{beginPath:null},{moveTo:[50,20]},{lineTo:[50,80]},{moveTo:[20,50]},{lineTo:[80,50]},{stroke:null},{strokeStyle:"17B3E8"},{lineWidth:"22"},{beginPath:null},{moveTo:[50,20]},{lineTo:[50,80]},{moveTo:[20,50]},{lineTo:[80,50]},{stroke:null}],translate:{x:0,y:0},scale:1}};(function(){var a=h.Ming.Canvas,b=Array.prototype.slice,e=a.heartIcon.draw,d=b.call(e,0,2),c=b.call(a.brokenHeartIcon.draw,0),g=b.call(e,2,e.length),b=a.fullscreenIcon.draw,e=a.unfullscreenIcon.draw;newFullscreenData=
a.fullscreenIcon.draw.slice(0);newUnfullscreenData=a.unfullscreenIcon.draw.slice(0);a.brokenHeartIcon.draw=d.concat(c).concat(g);for(d=1;d<4;d++){c=[{rotate:[d*90*(Math.PI/180)]}];newFullscreenData=newFullscreenData.concat(c,b);newUnfullscreenData=newUnfullscreenData.concat(c,e)}a.fullscreenIcon.draw=newFullscreenData;a.unfullscreenIcon.draw=newUnfullscreenData})();h.Ming.Intro=MingClass.extend({init:function(a,b){function e(){var c=b.element,d=c.q("."+Y),d=c.clientHeight-d.clientHeight+10;Math.max(g?g.clientHeight:0,j?j.clientHeight:0)+2*c.q("."+ra).computeStyle("padding-top").toInt()>=
d||n?a.addClass(I):a.removeClass(I)}function d(){n=!1;a.removeClass(I)}function c(){b.events.unbind(P,e)}var g=a.q("."+Ta),j=a.q("hgroup"),f=b.config.embed.pause_info,n=!1;this.element=a;f?b.events.bind(ua,d):b.events.bind(L,c);b.events.bind(na,function(){n=!0;a.addClass(I)}).bind(P,e).bind(Jb,function(){a.removeClass(I)})}});h.Ming.Controls=MingClass.extend({init:function(a,b){function e(){o.playButtonLocked||O.setData({icon:h.Ming.Canvas.playIcon}).refresh()}function d(){o.playButtonLocked||O.setData({icon:h.Ming.Canvas.pauseIcon}).refresh()}function c(){i.fire(L)}function g(){var c=b.config.embed.toggle.playbar,
d=b.element,e=d.clientWidth*0.8,f=d.clientHeight*0.8,g=k.clientWidth,i=k.clientHeight;(function(){k.style.webkitTransform="";d.removeClass(N);if(E){E.removeClass(Ra);this.fullScreenSupported&&E.removeClass(y)}})();if(!c||s.clientWidth<=50||d.clientWidth<Lc||d.clientHeight<a.clientHeight){d.addClass(N);if(E){E.addClass(Ra);var c=(e-k.clientWidth)/2,j=E.clientWidth+E.computeStyle("padding-right").toInt();c<j&&E.addClass(y)}}if(g>e||i>f){e=e>f?f/i:e/g;if(e>=1)return false;k.style.webkitTransform="scale("+
e+")"}}function j(a){var b=$m.floor(a/3600%60),c=$m.floor(a/60%60),a=$m.floor(a%60);return(b>0?b+":":"")+$m.pad(c,2)+":"+$m.pad(a,2)}function f(){e()}function n(){J.draw(A.draw,A.translate,A.scale,"fff",false)}function t(){J.draw(x.draw,x.translate,x.scale,"fff",false)}var o=this,i=b.events,s=a.q("."+qc),u=a.q("."+$c),r=a.q("."+sc),m=a.q("."+Tc),C=m&&m.q("span"),q=a.q("."+Uc),w=q&&q.q("span"),k=a.q("."+tb),D=a.q("."+Bb),E=a.q("."+Ia),G=E&&E.q("canvas"),B=a.q("."+Rc),z=a.q("."+Sc),p=a.q("."+Wa),H=
C.html(),O=new h.Ming.Sidedock.Button(k,b),J=new h.UI.CanvasElement(G),x=h.Ming.Canvas.fullscreenIcon,A=h.Ming.Canvas.unfullscreenIcon;h.Ming.Controls.BufferBar&&new h.Ming.Controls.BufferBar(B,b);h.Ming.Controls.Volume&&new h.Ming.Controls.Volume(z,b);o.element=a;o.fsButtonParent=E;o.fullScreenSupported=true;o.playButtonLocked=false;C.html(j(H));O.setData({icon:h.Ming.Canvas.playIcon}).refresh();k.addEventListener("click",c,false);p&&p.addEventListener("click",function(){i.fire(Nb)},false);if(G){J.draw(x.draw,
x.translate,x.scale,"fff",false);E.addEventListener("click",function(a){i.fire(Qb,b.controller.ua.win?a.ctrlKey:a.metaKey)},false);E.addEventListener("mouseover",function(){var a=b.config.embed,c=a.color;if(b.element.hasClass(N))c=E.computeStyle("background-color").rgb2hex()==="ffffff"?a.alt_color:"fff";else if(c==="ffffff"||c==="fff")c=a.alt_color;J.setColor(c).refresh()},false);G.addEventListener("mouseout",function(){J.setColor("fff").refresh()},false)}i.bind(Kb,function(a){u.style.width=(a.data*
100).round()+"%";u.attr("data-value",a.data)}).bind(na,function(){d()}).bind(ua,f).bind(Db,f).bind(ma,function(a){var b=a.data.hours>0?a.data.hours+":":"",c=(a.data.progress*100).round();r.style.width=c+"%";r.attr("data-value",a.data.progress);C.html(b+a.data.minutes.pad(2)+":"+a.data.seconds.pad(2));m.style.left=c+"%"}).bind(L,function(){k.removeEventListener("click",c,false);d();k.addEventListener("click",function(){i.fire(S)},false);if(b.config.embed.toggle.playbar){C.html("00:00");s.addEventListener("mousedown",
function(a){if(!a.button){o.playButtonLocked=true;var b=$m.position(r).x,c=0,d=a.target,f=s.computeStyle("width").toInt()-s.computeStyle("border-left-width").toInt()-s.computeStyle("border-right-width").toInt();document.webkitIsFullScreen&&(b=b-$m.position(document.webkitCurrentFullScreenElement).x);d.hasAncestor(C)&&(c=a.offsetX-C.clientWidth/2);var g=function(a){i.fire(mc,((a.pageX-b-c)/f).limit(0,1))};window.addEventListener("mousemove",g,false);g(a);window.addEventListener("mouseup",function U(){this.removeEventListener("mousemove",
g,false);this.removeEventListener("mouseup",U,false);i.fire(Tb);o.playButtonLocked=false;if(q){D.addEventListener("mousemove",e,false);q.css({display:"block"})}},false);if(q){D.removeEventListener("mousemove",e,false);q.css({display:"none",opacity:0});q.css("display","none")}i.fire(Sb)}},false);if(q){q.addEventListener(Ha,function(a){a.propertyName==="opacity"&&this.css("opacity")==0&&this.css("display","none")},false);var a=function(b){if($m.withinElement(s,b)){b.preventDefault();return false}q.css("display",
"block");setTimeout(function(){q.css("opacity",1)},0);s.removeEventListener("mouseover",a,false);D.addEventListener("mousemove",e,false);D.addEventListener("mouseout",f,false)},e=function(a){var b=s.computeStyle("border-left-width").toInt()+s.computeStyle("border-right-width").toInt(),c=s.computeStyle("width").toInt()-b,a=a.clientX-$m.position(s).x-b;m.css("left").toInt();var d=0;document.webkitIsFullScreen&&(a=a+$m.position(document.webkitCurrentFullScreenElement).x);d=$m.limit(a,-b,c);q.css({display:"block",
left:d+"px"});setTimeout(function(){q.css("opacity",1)},0);w.html(j($m.limit(a,0,c)/c*H))},f=function(b){if($m.withinElement(D,b)){b.preventDefault();return false}q.css("opacity",0);D.removeEventListener("mousemove",e,false);D.removeEventListener("mouseout",f,false);s.addEventListener("mouseover",a,false)};s.addEventListener("mouseover",a,false)}}}).bind($a,function(b){b.data.controls&&a.addClass(I)}).bind(va,function(b){b.data.controls&&a.removeClass(I)}).bind(P,function(){g()}).bind(gb,function(a){p&&
(a.data===Z?p.addClass(ka):p.removeClass(ka))}).bind(oc,function(){o.playButtonLocked=false;e();u.css("width",0);r.css("width",0);m.css("left",0).html(j(H))}).bind(Xb,n).bind(Zb,t).bind(Yb,n).bind($b,t);o.mousedOver=function(a){return a.hasAncestor(D)||a.hasAncestor(k)?true:false}},setFullScreenSupported:function(a){this.fullScreenSupported=a;this.fsButtonParent&&(a?this.fsButtonParent.removeClass(y):this.fsButtonParent.addClass(y))},lockPlayButton:function(){this.playButtonLocked=true},unlockPlayButton:function(){this.playButtonLocked=
false}});h.Ming.Controls.BufferBar=MingClass.extend({init:function(a,b){function e(){return c.computeStyle("width").toInt()-
c.computeStyle("border-left-width").toInt()-c.computeStyle("border-right-width").toInt()}function d(){f.clearRect(0,0,g,j);f.strokeStyle="#666";f.lineWidth=2;f.lineCap="square";f.beginPath();for(var a=offset;a<g+8;a=a+5){f.moveTo(a,0);f.lineTo(a-8,8)}f.closePath();f.stroke();offset++;offset>=0&&(offset=-5)}if(!a)return false;var c=a.parentNode,g=e(),j=a.attr("height").toInt(),f=a.getContext("2d");offset=-5;UPDATE_INTERVAL=30;interval=null;a.attr("width",g);a.css("width",g+"px");b.controller.playerMode===
pb&&a.css("width",g+"px");b.events.bind(wb,function(){clearInterval(interval);interval=setInterval(d,UPDATE_INTERVAL)}).bind(ab,function(){clearInterval(interval);interval=null;f.clearRect(0,0,g,j)}).bind(P,function(){g=e();a.attr("width",g);a.css("width",g+"px")})}});h.Ming.Controls.Volume=MingClass.extend({init:function(a,b){function e(a){m||(m=window.setInterval(d,r));for(var b=0;b<Gb;b++){var c=o[b],e=(i+s)*b,f=e+i;c.active=false;if(a>=e&&a<=f&&!c.active){c.value=u+1;c.active=true}}}function d(){j.clearRect(0,0,f,h);j.fillStyle="#666";j.fillRect(0,0,f,h);j.fillStyle="#"+b.config.embed.color;j.fillRect(0,0,t*f,h);for(var a=false,c,d,e=0;e<Gb;e++){c=
o[e]||{value:0,active:false};d=u-c.value;j.clearRect((i+s)*e+i,0,s,h);j.clearRect((i+s)*e,0,i,d.abs());if(c.value>0){c.value--;a=true}o[e]=c}if(!a){window.clearInterval(m);m=null}}if(!a)return false;var c=b.events,g=a.q("canvas"),j=g.getContext("2d"),f=g.width,h=g.height,t=1,o=[],i=3,s=2,u=3,r=50,m=null;g.addEventListener("mousemove",function(a){e(a.offsetX)},false);g.addEventListener("mousedown",function(a){if(!a.button){var b=$m.position(g).x,d=g.computeStyle("width").toInt(),f=offset=0;document.webkitIsFullScreen&&
(b=b-$m.position(document.webkitCurrentFullScreenElement).x);var i=function(a){offset=a.pageX-b;f=t=(offset/d).limit(0,1);c.fire(nc,f);e(offset)};window.addEventListener("mousemove",i,false);window.addEventListener("mouseup",function G(){this.removeEventListener("mousemove",i,false);this.removeEventListener("mouseup",G,false);c.fire(Vb)},false);i(a);c.fire(Ub)}},false);c.bind(Ob,function(a){t=a.data;m||(m=window.setInterval(d,r))}).bind(Eb,function(){d()})}});h.Ming.Sidedock=MingClass.extend({init:function(a,b){function e(a,b,c,d){a.element&&(a.setData({icon:b,onClick:c,active:d}),a.refresh())}function d(a){c();a.element.addClass(Qa)}function c(){var b=a.qa("button");b.length&&b.removeClass(Qa)}function g(){w.element&&
w.element.removeClass(y)}function j(){w.element&&w.element.addClass(y)}var f=this,n=b.events;new XHR;var M=b.config,o=h.Ming.Canvas,i=h.Ming.Sidedock,s=i.ToggleButton,i=i.Button,u=new s(a.q("."+xc),b),r=new s(a.q("."+yc),b),m=new i(a.q("."+Ca),b),C=new i(a.q("."+zc),b),q=new i(a.q("."+Ac),b),w=new s(a.q("."+Bc),b);f.element=a;f.ming=b;f.enable();e(u,o.heartIcon,function(){f.enabled&&n.fire(fa)},M.user.liked);e(r,o.watchLaterIcon,function(){f.enabled&&n.fire(hb,r)},M.user.watch_later);e(m,o.shareIcon,
function(){f.enabled&&n.fire(ib,m)});e(C,o.embedIcon,function(){f.enabled&&n.fire(wa,C)});e(q,o.voteIcon,function(){f.enabled&&n.fire(La,q)});e(w,null,function(){f.enabled&&n.fire(Wb,w)},M.request.cookie.scaling);w.element&&w.element.addClass(y);n.bind($a,function(b){b.data.sidedock&&a.addClass(I)}).bind(va,function(b){b.data.sidedock&&a.removeClass(I)}).bind(X,function(){c()}).bind(P,function(){f.updateLayout()}).bind(Eb,function(){u.refresh();r.refresh()}).bind(fa,function(){if(M.user.status.logged_in)u.onToggle();
else d(u)}).bind(hb,function(){if(M.user.status.logged_in)r.onToggle();else d(r)}).bind(ib,function(){d(m)}).bind(wa,function(){d(C)}).bind(La,function(){d(q)}).bind(Wb,function(){w.onToggle()}).bind(L,function(){a.removeClass(yb)}).bind(Xb,g).bind(Yb,g).bind(Zb,j).bind($b,j);f.mousedOver=function(b){return b.hasAncestor(a)?!0:!1}},enable:function(){this.enabled=!0},disable:function(){this.enabled=!1},updateLayout:function(){function a(){var e=f&&n?f.clientHeight+n.clientHeight:d.clientHeight;if(c.clientHeight<
fc)c.addClass(N),g.addClass(y);else{if(e<=h)return!1;(e=b())&&a()}}function b(a){f||(f=document.createElement("div").addClass(ob),d.prependChild(f));n||(n=d.qa("."+Ra).wrap("div",Sa));if(1==n.childNodes.length)return!1;var c=n.q("."+Ra),e=c.computeStyle("margin-left").toInt();f.appendChild(c);f.style.width=f.childNodes.length*(c.clientWidth+e)+"px";return a?b(a):!0}var e=this,d=e.element,c=e.ming.element,g=c.q("."+ra),j=c.q("."+Y),f=d.q("."+ob),n=d.q("."+Sa),h=c.clientHeight-j.clientHeight+10;(function(){function a(b){if(b){for(var c=
b.qa("button"),e=0,f=c.length;e<f;e++)d.appendChild(c[e]);b.remove()}}e.ming.config.embed.toggle.playbar&&c.removeClass(N);d.removeClass(y);g.removeClass(y);a(f);a(n);f=n=null})();a();c.clientWidth<gc&&d.addClass(y)}});h.Ming.Sidedock.ButtonBase=MingClass.extend({init:function(a,
b){if(!a)return!1;var e=a.q("canvas");this.element=a;this.ming=b;this.icon=e?new h.UI.CanvasElement(e):null;this.setupEvents()},setupEvents:function(){},addEvent:function(a,b){this.element.addEventListener(a,b,!1)},removeEvent:function(a,b){this.element.removeEventListener(a,b,!1)},setData:function(a){this.data=a;this.data.onClick&&this.addEvent("click",this.data.onClick);return this},refresh:function(){if(this.icon){var a="ffffff"===this.element.computeStyle("background-color").rgb2hex()?this.ming.config.embed.alt_color:
"fff",b=this.data.icon;this.icon.draw(b.draw,b.translate,b.scale,a)}}});h.Ming.Sidedock.Button=h.Ming.Sidedock.ButtonBase;h.Ming.Sidedock.Button=h.Ming.Sidedock.ButtonBase.extend({init:function(a,b){this._super(a,b)},setupEvents:function(){var a=this,b=function(){a.refresh()};a.addEvent("mouseover",b);a.addEvent("mouseout",b)}});h.Ming.Sidedock.ToggleButtonBase=h.Ming.Sidedock.ButtonBase.extend({init:function(a,b){if(!a)return false;this.isActive=false;this._super(a,b)},setData:function(a){this._super(a);
this.setIsActive(this.data.active)},refresh:function(){if(this.icon){var a=this.ming.config.embed.color,b=this.ming.config.embed.alt_color,e=this.element.computeStyle("background-color").rgb2hex(),a=a==="ffffff"?b:a,d=this.data.icon;this.icon.draw(d.draw,d.translate,d.scale,this.isActive?a:e==="ffffff"?b:"fff",a===e&&this.isActive)}},getIsActive:function(){return this.isActive},setIsActive:function(a){this.isActive=a==1;a?this.element.addClass(ka):this.element.removeClass(ka)},onToggle:function(){this.setIsActive(!this.isActive);
this.refresh()}});h.Ming.Sidedock.ToggleButton=h.Ming.Sidedock.ToggleButtonBase;h.Ming.Sidedock.ToggleButton=
h.Ming.Sidedock.ToggleButtonBase.extend({init:function(a,b){this._super(a,b)},setupEvents:function(){var a=this,b=function(){a.refresh()};a.addEvent("mouseover",b);a.addEvent("mouseout",b)}});
h.Ming.Overlays=MingClass.extend({init:function(a,b,e,d){function c(){if(f.data.isSticky)return false;d.events.fire(X)}function g(){d.element.q("."+Y).removeClass(y);a.removeClass(N);d.element.q("."+ra).removeClass(y)}function j(){if(!f.current)return false;var b=d.element,c=b.q("."+ra),e=b.q("."+xa),i=b.q("."+Y);g();b.clientHeight<Mc?a.addClass(N):a.removeClass(N);var j=b.hasClass(N)?0:i.clientHeight,h=e.q("."+ob),n=e.q("."+Sa),o=Math.round(b.clientWidth/2-a.clientWidth/2),s=Math.round(b.clientHeight/
2-a.clientHeight/2-j/2)+10,h=h?h.clientHeight+10:0;sdWidth=(n?n.clientWidth:e.clientWidth)+10;a.style.left=o+"px";a.style.top=s+"px";(s<h||o<sdWidth||b.clientHeight<fc)&&c.addClass(y);if(s+a.clientHeight>=b.clientHeight-i.clientHeight){i.addClass(y);a.style.top=s+j/2-10+"px"}}var f=this,h=d.config,M=false,o=d.element.q("."+rc),i=d.element.q("."+pa),s={},u=new XHR;f.element=a;f.current="";f.data={};f.config=h;f.get=function(c){function g(){a.innerHTML=s[c.name];a.prependChild(s.style);d.element.addClass(c.isToggle?
ac:"");var b=a.q("script");b&&(new Function(b.innerHTML)).call(f.config);setTimeout(function(){f.show()},100)}function i(){M=true;var a=c.name;u.get(b+"/ming_overlay_"+a+".html?"+(new Date).getTime(),function(b){if(!M||!b){d.events.fire(X);return false}s[a]=b;if(s.style){M=false;g()}else j(g)})}function j(a){u.get(e,function(b){if(!M){d.events.fire(X);return false}var c=document.createElement("style");c.innerText=b;s.style=c;M=false;a.call(f)})}if(f.current===c.name||M){d.events.fire(X);M=false}else if(f.current&&
f.current!=c.name)f.hide(c);else if(!(c.name==="outro"&&h.embed.outro.type=="nothing"))if(c.name==="embed"&&typeof embedWindowPopup!="undefined"||c.name==="share"&&typeof shareWindowPopup!="undefined"){var o=function(){c.name==="embed"?embedWindowPopup(h.video.id):c.name==="share"&&shareWindowPopup(h.video.id)};if(d.element.hasClass(Ia)){d.exitFullscreen();document.addEventListener("webkitfullscreenchange",function D(){document.removeEventListener("webkitfullscreenchange",D,false);document.webkitIsFullScreen||
setTimeout(o,100)},false)}else o();d.events.fire(X)}else{f.data=c;s[c.name]?g():i()}};f.show=function(){function b(){e.addClass(Ya);d.element.addClass(O);if(!o.hasClass(y)){o.addEventListener("click",c,false);i.addEventListener("click",c,false);document.q("."+O+" ."+pa);d.ancestors.contains(i)||d.ancestors.push(i)}if(f.data.isToggle){var a=parseFloat(e.computeStyle("-webkit-transition-duration"))*1E3;setTimeout(function(){d.events.fire(X)},f.data.hideTime+a)}}f.current=f.data.name;var e=a.q("."+O);
a.removeClass(y);o.removeClass(y);j();setTimeout(function(){b()},10)};f.hide=function(b){function e(){d.element.removeClass(ac);h.removeClass(Za);if(b){a.innerHTML="";f.get(b)}else{a.addClass(y);if(!o.hasClass(y)){o.addClass(y);o.removeEventListener("click",c,false);i.removeEventListener("click",c,false)}}d.element.removeEventListener(Ha,e,false);g();d.events.fire(P)}var h=a.q("."+O);if(!h)return false;d.element.addEventListener(Ha,e,false);h.removeClass(Ya);h.addClass(Za);j();f.current="";b||d.element.removeClass(O)};
d.events.bind(L,c).bind(S,c).bind(na,c).bind(P,j)}});